[package]
name = "purs"
version = "0.1.0"
authors = ["Xavier Cambar <xcambar@gmail.com>"]
edition = "2018"

[dependencies]
ansi_term = "0.11"
clap = { version = "4.4.11", features = ["derive", "env"] }
dirs = "2.0"
git2 = "0.8"
tico = "1.0.0"
